// Generated by scripts/generate-persisted-operations.mjs. Do not edit.
export const persistedOperationIds = {
  "AbortGame": "110d082d51f12e58d8879bfe00c279ef0da56f70103c02d9184749c8766d6697",
  "CreateCloudDeck": "b2c7f6bdd87f3dcda94dd1310a06f76fa87278d83463fae38ee272364ce10604",
  "CreateLobby": "e0232757e4a9f4309b8eaee14864c36faaf660c5ba14c993987502d2c86ab00a",
  "CreateSocketTicket": "74b8439012215c1b388d063fda471963eebde1977b47750711d8141b81372ac6",
  "DeckFromUrl": "e2d54cb06896455b1e475ccd5c105cf6bdb9150941ca679ee1173603e175fc27",
  "DeleteCloudDeck": "6105c8818bc8f4e8df5c81c3bff47e7765dea7577d91b9a4c046b5574489eb7c",
  "DeleteLobby": "b6d00ee20fc57791e3da08d600bab1e34d2a032bb76826eb315761f610af59ef",
  "JoinLobby": "adad48f5ea3c9cd1dd60a1c7667fc1ef871e3e1dee04b39bce7f642ef1b0c1ef",
  "Lobby": "4989715e0a20d509a135f7aac2458be5dcaac27659981ab2dfda804bdcfdb6d9",
  "PublicLobbies": "187eec18c6d79160d78050b127e87af0cf571e6d1efb274faddf1f6f761e422b",
  "RegisterDeck": "327276299c64941653a9ece3bcf32600e7886ad444b70c2d88f7b00c175c1fe4",
  "StartGame": "ccfa351e57f00d00175bd38c89e39b5d9318925690d6f9b2ef3fbc1393c2fc3a",
  "UpdateCloudDeck": "a6df754f4c4d57f84f3bcd837fd8ff64fc7b7585592eb31a6ba43453074c49c8",
} as const
