name = "mtg-battle-mode-import"
main = "src/index.js"
compatibility_date = "2026-07-01"
compatibility_flags = ["global_fetch_strictly_public"]

[vars]
RELEASE_VERSION = "local"
ALLOWED_ORIGIN = "http://localhost:5173,https://mtgbattlearena.nl,https://www.mtgbattlearena.nl,https://mtgbattlearena.web.app"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1

[env.staging]
name = "mtg-battle-mode-import-staging"

[env.staging.vars]
RELEASE_VERSION = "local"
ALLOWED_ORIGIN = "http://localhost:5173,https://beta.mtgbattlearena.nl,https://mtgbattlearena-beta.web.app,https://mtgbattlearena-beta.firebaseapp.com"
